version: '2'

services:
  xserver:
    build: ./docker-materials/xvfb/
    restart: unless-stopped
    networks:
      - devbox-net
    environment:
      - DISPLAY_WIDTH=1440
      - DISPLAY_HEIGHT=900

  vncserver:
    build: ./docker-materials/x11vnc/
    restart: always
    restart: unless-stopped
    networks:
      - devbox-net
    environment:
      - DISPLAY=xserver:0.0
    ports:
      - "5900:5900"

  desktop-base:
    build: ./docker-materials/xfce/
    environment:
      - DISPLAY=xserver:0.0
    networks:
      - devbox-net

  novnc:
    build: ./docker-materials/novnc/
    restart: unless-stopped
    command: ["--vnc", "vncserver:5900"]
    ports:
      - "9000:9000"
    networks:
      - devbox-net

networks:
  devbox-net:
